[2021-11-20 21:25:39,020] {processor.py:163} INFO - Started process (PID=16937) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
[2021-11-20 21:25:39,021] {processor.py:625} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-20 21:25:39,021] {logging_mixin.py:109} INFO - [2021-11-20 21:25:39,021] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
[2021-11-20 21:25:39,031] {logging_mixin.py:109} INFO - [2021-11-20 21:25:39,030] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-20 21:25:39,040] {processor.py:639} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
[2021-11-20 21:25:39,046] {processor.py:171} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-20 21:26:13,764] {processor.py:163} INFO - Started process (PID=16973) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
[2021-11-20 21:26:13,765] {processor.py:625} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-20 21:26:13,766] {logging_mixin.py:109} INFO - [2021-11-20 21:26:13,766] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
[2021-11-20 21:26:13,775] {logging_mixin.py:109} INFO - [2021-11-20 21:26:13,774] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-20 21:26:13,784] {processor.py:639} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py
[2021-11-20 21:26:13,790] {processor.py:171} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/example_python_operator.py took 0.029 seconds
