[2021-11-20 21:25:27,173] {processor.py:163} INFO - Started process (PID=16927) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-20 21:25:27,198] {processor.py:625} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-20 21:25:27,207] {logging_mixin.py:109} INFO - [2021-11-20 21:25:27,207] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-20 21:25:27,324] {logging_mixin.py:109} INFO - [2021-11-20 21:25:27,323] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.9/dist-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-20 21:25:27,374] {processor.py:639} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-20 21:25:27,400] {processor.py:171} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.354 seconds
[2021-11-20 21:26:03,857] {processor.py:163} INFO - Started process (PID=16962) to work on /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-20 21:26:03,858] {processor.py:625} INFO - Processing file /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-20 21:26:03,859] {logging_mixin.py:109} INFO - [2021-11-20 21:26:03,859] {dagbag.py:500} INFO - Filling up the DagBag from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-20 21:26:03,875] {logging_mixin.py:109} INFO - [2021-11-20 21:26:03,873] {dagbag.py:334} ERROR - Failed to import: /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/usr/local/lib/python3.9/dist-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-20 21:26:03,886] {processor.py:639} WARNING - No viable dags retrieved from /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-20 21:26:03,893] {processor.py:171} INFO - Processing /usr/local/lib/python3.9/dist-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.040 seconds
